---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-scylla
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Nothing for now

script:
  # Run tests.
  - molecule test
