---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-scylla
  matrix:
    - MOLECULE_DISTRO: centos7
      SCYLLADB_REPO_URL: $SCYLLADB_CENTOS_REPO_URL

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Nothing for now
  - echo "Before script handler"

script:
  # Run tests.
  - molecule test
